#!/usr/bin/python2

from datetime import datetime
import time, subprocess, sys, os

work=["6:34", "6:56", "7:04", "7:22", "7:34", "7:46", "7:56", "8:27", "9:01", "10:01", "11:01", "11:46", "12:06", "12:37", "12:42", "13:42", "14:12", "14:42", "15:47", "16:06", "16:22", "16:47", "17:06", "17:37", "18:10", "18:46", "20:57", "23:56"]

def get_sec(time_str):
    h, m = time_str.split(':')
    return int(h) * 3600 + int(m) * 60

param1 = sys.argv[1]
time_now = get_sec(datetime.now().strftime("%H:%M"))
#time_now = get_sec("17:05")
time_diff = 99999
output = 0

for i in work:
    previous = time_diff
    time_next = get_sec(i)
    if time_next > time_now:
        time_diff = time_next - time_now
    if time_diff < previous:
        output = time_diff

message = 'The next Bus comes in: ' +  str(output / 60) + ' minutes'

if output / 60 == 1 and int(datetime.now().strftime("%S")) < 10 and int(datetime.now().strftime("%H")) >= 16:
    message = 'The next Bus comes in: ' +  str(output / 60) + ' minute'

if output / 60 < 5 and int(datetime.now().strftime("%S")) < 10 and int(datetime.now().strftime("%H")) >= 16:
    subprocess.call(['notify-send', '-u', 'normal', message])
    print output / 60, "minutes"

if output / 60 == 1:
    print output / 60, "minute"
else:
    print output / 60, "minutes"

if param1 == "1":
    subprocess.call(['conky', '--text', 'test'])
if param1 == "2":
    os.system("killall -9 conky")
